workspace:
  base: /go
  path: src/github.com/journeymidnight/yig
pipeline:
  build:
    image: centos:7.2.1511
    commands:
      # ceph
      - yum install -y epel-release
      - rpm -ivh https://download.ceph.com/rpm-luminous/el7/noarch/ceph-release-1-1.el7.noarch.rpm
      - yum install -y libradosstriper-devel
      #go
      - yum install -y golang git
      - yum install -y rpm-build make
      - bash package/rpmbuild.sh
  pushbear:
    image: thesues/drone-pushbear
    url: XXXX
    secrets: [sendkey]
  github_release:
    image: plugins/github-release
    files:
      - "yig*.x86_64.rpm"
    secrets: [github_token]
    when:
      event: [tag]
