clone:
  tags: true
  depth: 50
  when:
    branch: master
build:
  image: plato/build
  commands:
    - export GOPATH=/app/src/github.com/journeymidnight/yig/build
    - mkdir -p /app/src/github.com/journeymidnight
    - ln -s `pwd` /app/src/github.com/journeymidnight/yig
    - cd /app/src/github.com/journeymidnight/yig
    - yum-config-manager --add-repo  http://s3s.lecloud.com/ceph-jewel/el7/update/
    - yum-config-manager --add-repo  http://10.110.122.221/7/epel/
    - yum install --nogpgcheck -y ceph-devel
    - bash package/rpmbuild.sh
    - bash cipostbuild.sh
  when:
    branch: master