clone:
  tags: true
  depth: 50
build:
  image: plato/build
  commands:
    - export GOPATH=/app/src/legitlab.letv.cn/yig/yig/build
    - mkdir -p /app/src/legitlab.letv.cn/yig
    - ln -s `pwd` /app/src/legitlab.letv.cn/yig/yig
    - cd /app/src/legitlab.letv.cn/yig/yig
    - yum-config-manager --add-repo  http://s3s.lecloud.com/ceph-jewel/el7/update/
    - yum-config-manager --add-repo  http://10.110.122.221/7/epel/
    - yum install --nogpgcheck -y ceph-devel
    - bash package/rpmbuild.sh
    - bash cipostbuild.sh
notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    when:
      success: true
      failure: true
      change: true
