clone:
  tags: true
  depth: 50
build:
  image: plato/build
  commands:
    - export GOPATH=/app/src/legitlab.letv.cn/yig/yig/build
    - mkdir -p /app/src/legitlab.letv.cn/yig
    - ln -s `pwd` /app/src/legitlab.letv.cn/yig/yig
    - cd /app/src/legitlab.letv.cn/yig/yig
    - yum-config-manager --add-repo  http://s3s.lecloud.com/ceph-jewel/el7/update/
    - yum-config-manager --add-repo  http://10.110.122.221/7/epel/
    - yum install --nogpgcheck -y ceph-devel
    - bash package/rpmbuild.sh
    - bash cipostbuild.sh

